name: Production Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run production tests
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        pytest validation/test_production_metrics.py -v --tb=short
      timeout-minutes: 3
    
    - name: Validate cost targets
      run: |
        export PYTHONPATH=$PWD:$PYTHONPATH
        python -c "
        from core.supervisor import run_compliance_check
        result = run_compliance_check('CI-TEST-001')
        assert result.total_cost <= 0.04, f'Cost {result.total_cost} exceeds budget'
        print(f'✓ Cost check passed: \${result.total_cost:.4f}')
        "
